[2024-05-18T14:54:54.171+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v2.wget manual__2024-05-18T14:52:51.410367+00:00 [queued]>
[2024-05-18T14:54:54.178+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v2.wget manual__2024-05-18T14:52:51.410367+00:00 [queued]>
[2024-05-18T14:54:54.179+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 11
[2024-05-18T14:54:54.193+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): wget> on 2024-05-18 14:52:51.410367+00:00
[2024-05-18T14:54:54.201+0000] {standard_task_runner.py:60} INFO - Started process 1783 to run task
[2024-05-18T14:54:54.204+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v2', 'wget', 'manual__2024-05-18T14:52:51.410367+00:00', '--job-id', '326', '--raw', '--subdir', 'DAGS_FOLDER/frist-dag.py', '--cfg-path', '/tmp/tmphhf8jq29']
[2024-05-18T14:54:54.206+0000] {standard_task_runner.py:88} INFO - Job 326: Subtask wget
[2024-05-18T14:54:54.246+0000] {task_command.py:423} INFO - Running <TaskInstance: our_first_dag_v2.wget manual__2024-05-18T14:52:51.410367+00:00 [running]> on host 7b23a6949395
[2024-05-18T14:54:54.318+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='omar' AIRFLOW_CTX_DAG_ID='our_first_dag_v2' AIRFLOW_CTX_TASK_ID='wget' AIRFLOW_CTX_EXECUTION_DATE='2024-05-18T14:52:51.410367+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-18T14:52:51.410367+00:00'
[2024-05-18T14:54:54.320+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-18T14:54:54.321+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'wget https://d37ci6vzurychx.cloudfront.net/misc/taxi_zone_lookup.csv']
[2024-05-18T14:54:54.334+0000] {subprocess.py:86} INFO - Output:
[2024-05-18T14:54:54.336+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: wget: command not found
[2024-05-18T14:54:54.336+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-05-18T14:54:54.345+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-05-18T14:54:54.348+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=our_first_dag_v2, task_id=wget, execution_date=20240518T145251, start_date=20240518T145454, end_date=20240518T145454
[2024-05-18T14:54:54.360+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 326 for task wget (Bash command failed. The command returned a non-zero exit code 127.; 1783)
[2024-05-18T14:54:54.377+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-18T14:54:54.399+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
