[2024-06-12T18:08:37.796+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: our_first_dag_v2.seceond_task scheduled__2024-06-06T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
