[2024-05-18T14:53:48.293+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v2.wget manual__2024-05-18T14:51:44.788551+00:00 [queued]>
[2024-05-18T14:53:48.300+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v2.wget manual__2024-05-18T14:51:44.788551+00:00 [queued]>
[2024-05-18T14:53:48.301+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 11
[2024-05-18T14:53:48.314+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): wget> on 2024-05-18 14:51:44.788551+00:00
[2024-05-18T14:53:48.321+0000] {standard_task_runner.py:60} INFO - Started process 1759 to run task
[2024-05-18T14:53:48.324+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v2', 'wget', 'manual__2024-05-18T14:51:44.788551+00:00', '--job-id', '324', '--raw', '--subdir', 'DAGS_FOLDER/frist-dag.py', '--cfg-path', '/tmp/tmp0anwp6h3']
[2024-05-18T14:53:48.325+0000] {standard_task_runner.py:88} INFO - Job 324: Subtask wget
[2024-05-18T14:53:48.365+0000] {task_command.py:423} INFO - Running <TaskInstance: our_first_dag_v2.wget manual__2024-05-18T14:51:44.788551+00:00 [running]> on host 7b23a6949395
[2024-05-18T14:53:48.432+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='omar' AIRFLOW_CTX_DAG_ID='our_first_dag_v2' AIRFLOW_CTX_TASK_ID='wget' AIRFLOW_CTX_EXECUTION_DATE='2024-05-18T14:51:44.788551+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-18T14:51:44.788551+00:00'
[2024-05-18T14:53:48.434+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-18T14:53:48.435+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'wget https://d37ci6vzurychx.cloudfront.net/misc/taxi_zone_lookup.csv']
[2024-05-18T14:53:48.448+0000] {subprocess.py:86} INFO - Output:
[2024-05-18T14:53:48.450+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: wget: command not found
[2024-05-18T14:53:48.450+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-05-18T14:53:48.459+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-05-18T14:53:48.463+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=our_first_dag_v2, task_id=wget, execution_date=20240518T145144, start_date=20240518T145348, end_date=20240518T145348
[2024-05-18T14:53:48.475+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 324 for task wget (Bash command failed. The command returned a non-zero exit code 127.; 1759)
[2024-05-18T14:53:48.496+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-18T14:53:48.517+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
